name: Matrix
on: push

jobs:
  node-version:
    runs-on: macos-latest
    steps:
      - name: Log Node Version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log Node Version
        run: node -v
